title: Threats Across the AI Lifecycle
description: Full, detailed content — Intro, Data Engineering, Experiment/Development, Production

# Correct base URLs for a project site (icpinto/ai-lifecycle-threats)
url: https://icpinto.github.io
baseurl: /ai-lifecycle-threats

# Just the Docs theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Theme settings
color_scheme: dark
search_enabled: true
nav_external_links_new_tab: true

aux_links:
  "View on GitHub":
    - "https://github.com/icpinto/ai-lifecycle-threats"